/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Register;

import Register.My_CNX;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.*;
import javax.swing.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Login.Login;
import Main.Lobby;
/**
 *
 * @author 박주형
 */
public class Register extends javax.swing.JFrame {

    int mouseX;
    int mouseY;
    //public static String Nick;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RightPanel = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        Minimize = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        NickName = new javax.swing.JTextField();
        ConfirmPassword = new javax.swing.JPasswordField();
        AgeLabel = new javax.swing.JLabel();
        nickNameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BackKey = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        RightPanel.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout RightPanelLayout = new javax.swing.GroupLayout(RightPanel);
        RightPanel.setLayout(RightPanelLayout);
        RightPanelLayout.setHorizontalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        RightPanelLayout.setVerticalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        MainPanel.setBackground(new java.awt.Color(249, 249, 249));
        MainPanel.setMaximumSize(new java.awt.Dimension(2000, 1000));
        MainPanel.setPreferredSize(new java.awt.Dimension(1100, 622));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginLabel.setFont(new java.awt.Font("나눔스퀘어라운드 Regular", 1, 36)); // NOI18N
        LoginLabel.setText("회원가입");
        MainPanel.add(LoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        ageField.setForeground(new java.awt.Color(204, 204, 204));
        ageField.setText("나이 (숫자만 입력해주세요)");
        ageField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageFieldFocusLost(evt);
            }
        });
        ageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFieldActionPerformed(evt);
            }
        });
        MainPanel.add(ageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 280, 20));

        RegisterButton.setBackground(new java.awt.Color(0, 84, 140));
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("회원가입");
        RegisterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseClicked(evt);
            }
        });
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        MainPanel.add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 110, 50));

        PasswordField.setForeground(new java.awt.Color(204, 204, 204));
        PasswordField.setText("password");
        PasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusLost(evt);
            }
        });
        MainPanel.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 280, 30));

        Minimize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Minimize.setText(" -");
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeMouseExited(evt);
            }
        });
        MainPanel.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        Close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Close.setText(" x");
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
        });
        MainPanel.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        IDField.setForeground(new java.awt.Color(204, 204, 204));
        IDField.setText("아이디");
        IDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDFieldFocusLost(evt);
            }
        });
        MainPanel.add(IDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 280, 30));

        NickName.setForeground(new java.awt.Color(204, 204, 204));
        NickName.setText("닉네임");
        NickName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NickNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NickNameFocusLost(evt);
            }
        });
        MainPanel.add(NickName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 280, 30));

        ConfirmPassword.setForeground(new java.awt.Color(204, 204, 204));
        ConfirmPassword.setText("password");
        ConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ConfirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ConfirmPasswordFocusLost(evt);
            }
        });
        ConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordActionPerformed(evt);
            }
        });
        MainPanel.add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 280, 30));

        AgeLabel.setFont(new java.awt.Font("나눔스퀘어라운드 Regular", 1, 12)); // NOI18N
        AgeLabel.setText("나이");
        MainPanel.add(AgeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        nickNameLabel.setFont(new java.awt.Font("나눔스퀘어라운드 Regular", 1, 12)); // NOI18N
        nickNameLabel.setText("닉네임");
        MainPanel.add(nickNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("나눔스퀘어라운드 Regular", 1, 12)); // NOI18N
        jLabel3.setText("아이디");
        MainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("나눔스퀘어라운드 Regular", 1, 12)); // NOI18N
        jLabel4.setText("비밀번호");
        MainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        ConfirmPasswordLabel.setFont(new java.awt.Font("나눔스퀘어라운드 Regular", 1, 12)); // NOI18N
        ConfirmPasswordLabel.setText("비밀번호 확인");
        MainPanel.add(ConfirmPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        BackKey.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackKey.setForeground(new java.awt.Color(204, 204, 204));
        BackKey.setText("<");
        BackKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackKeyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackKeyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackKeyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackKey)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackKey, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        MainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(357, 357, 357)
                            .addComponent(RightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1136, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(RightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(379, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
        // TODO add your handling code here:
        Close.setForeground(Color.red);
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
        // TODO add your handling code here:
        Close.setForeground(Color.black);
    }//GEN-LAST:event_CloseMouseExited

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(Register.ICONIFIED);

    }//GEN-LAST:event_MinimizeMouseClicked

    private void MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseEntered
        // TODO add your handling code here:
        Minimize.setForeground(Color.gray);
    }//GEN-LAST:event_MinimizeMouseEntered

    private void MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseExited
        // TODO add your handling code here:
        Minimize.setForeground(Color.black);
    }//GEN-LAST:event_MinimizeMouseExited

    private void ageFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFieldFocusGained
        // TODO add your handling code here:
        if(ageField.getText().trim().toLowerCase().equals(("나이 (숫자만 입력해주세요)"))) {
            ageField.setText("");
            ageField.setForeground(Color.black);
        }
        Border idBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        ageField.setBorder(idBorder);
    }//GEN-LAST:event_ageFieldFocusGained

    private void ageFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFieldFocusLost
        // TODO add your handling code here:
        if(ageField.getText().trim().equals("") || ageField.getText().trim().toLowerCase().equals(("나이 (숫자만 입력해주세요)"))) {
            ageField.setText("나이 (숫자만 입력해주세요)");
            ageField.setForeground(new Color(153,153,153));
        }

        ageField.setBorder(null);
    }//GEN-LAST:event_ageFieldFocusLost

    private void RegisterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterButtonMouseClicked

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:

        PreparedStatement st;
        ResultSet rs;
        
        String nickname = NickName.getText();
        String ID = IDField.getText();
        String password = String.valueOf(PasswordField.getPassword());
        String Confirm = String.valueOf(ConfirmPassword.getPassword());
        String age = ageField.getText();
        
 
         String query = "INSERT INTO `users`(`username`, `password`, `age`, `nickname`) VALUES (?,?,?,?)";

        try {
            if(allinputed()) {
                if(!DupiID()) {
                    if(!DupiName()) {
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, ID);
            st.setString(2, password);
            st.setString(3, age);
            st.setString(4, nickname);
              
            if(st.executeUpdate()!=0) {
            //     Nick = nickname;
                JOptionPane.showMessageDialog(null, "회원가입 완료 되었습니다 \n 로그인 해주세요","회원가입 완료", 1);
                this.dispose();
            }
                }
            } else {
                JOptionPane.showMessageDialog(null, "정확히 다시 입력해주세요","회원가입 오류", 2);
            
     
            }
            }
        }
        catch (SQLException ex) {

            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void IDFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusGained
        // TODO add your handling code here:
        if(IDField.getText().trim().toLowerCase().equals(("아이디"))) {
            IDField.setText("");
            IDField.setForeground(Color.black);
        }
         Border idBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        IDField.setBorder(idBorder);
    }//GEN-LAST:event_IDFieldFocusGained

    private void IDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusLost
        // TODO add your handling code here:
           if(IDField.getText().trim().equals("") || IDField.getText().trim().toLowerCase().equals(("아이디"))) {
            IDField.setText("아이디");
            IDField.setForeground(new Color(153,153,153));
        }
          
          IDField.setBorder(null);
    }//GEN-LAST:event_IDFieldFocusLost

    private void ageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFieldActionPerformed

    private void NickNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NickNameFocusGained
        // TODO add your handling code here:
           if(NickName.getText().trim().toLowerCase().equals(("닉네임"))) {
            NickName.setText("");
            NickName.setForeground(Color.black);
        }
         Border idBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        NickName.setBorder(idBorder);
    }//GEN-LAST:event_NickNameFocusGained

    private void NickNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NickNameFocusLost
        // TODO add your handling code here:
          if(NickName.getText().trim().equals("") || NickName.getText().trim().toLowerCase().equals(("닉네임"))) {
            NickName.setText("닉네임");
            NickName.setForeground(new Color(153,153,153));
        }
          
          NickName.setBorder(null);
    }//GEN-LAST:event_NickNameFocusLost

    private void ConfirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmPasswordFocusGained
        // TODO add your handling code here:
           String pass2 = String.valueOf(ConfirmPassword.getPassword());
        if(pass2.trim().toLowerCase().equals(("password"))) {
            ConfirmPassword.setText("");
            ConfirmPassword.setForeground(Color.black);
        }
        Border idBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        ConfirmPassword.setBorder(idBorder);
    }//GEN-LAST:event_ConfirmPasswordFocusGained

    private void ConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmPasswordFocusLost
        // TODO add your handling code here:
         String pass2 = String.valueOf(ConfirmPassword.getPassword());
        if(pass2.trim().equals("") || pass2.trim().toLowerCase().equals(("password"))) {
            ConfirmPassword.setText("password");
            ConfirmPassword.setForeground(new Color(153,153,153));
        }
        
          ConfirmPassword.setBorder(null);
    }//GEN-LAST:event_ConfirmPasswordFocusLost

    private void PasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusLost
        // TODO add your handling code here:
        String pass = String.valueOf(PasswordField.getPassword());
        if(pass.trim().equals("") || pass.trim().toLowerCase().equals(("password"))) {
            PasswordField.setText("password");
            PasswordField.setForeground(new Color(153,153,153));
        }

        PasswordField.setBorder(null);
    }//GEN-LAST:event_PasswordFieldFocusLost
    public boolean allinputed() {
        String name = NickName.getText();
        String id = IDField.getText();
        String password = String.valueOf(PasswordField.getPassword());
        String Confirm = String.valueOf(ConfirmPassword.getPassword());
        String age = ageField.getText();
        
        if(name.equals("닉네임") || id.equals("아이디") || password.equals("password") || Confirm.equals("password")|| age.equals("나이 (숫자만 입력해주세요)")) {
        JOptionPane.showMessageDialog(null, "입력하지 않은 칸이 존재합니다", "확인", 2);
        return false;
        } 
        if(!password.equals(Confirm)) {
        JOptionPane.showMessageDialog(null, "비밀번호가 동일하지 않습니다", "확인", 2);
        return false;
        }
        if(!password.equals(Confirm)) {
        JOptionPane.showMessageDialog(null, "비밀번호가 동일하지 않습니다", "확인", 2);
        return false;
        }else {
        return true;
        }
    }
    
    public boolean DupiID() {
        PreparedStatement st;
        ResultSet rs;
        
        String username = IDField.getText();
        boolean Dupi = false;
        String query = "SELECT * FROM `users` WHERE `username` = ?";
        
        try {
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
            if(rs.next()) {
                System.out.println("중복된 아이디");
                 JOptionPane.showMessageDialog(null, "중복된 아이디입니다","회원가입 오류", 2);
                Dupi = true;
        } else {
            
                 Dupi = false;
            }
        }
                catch (SQLException ex) {
                
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Dupi;
    }
     public boolean DupiName() {
        PreparedStatement st;
        ResultSet rs;
        
        String nickname = NickName.getText();
        boolean Dupi = false;
        String query = "SELECT * FROM `users` WHERE `nickname` = ?";
        
        try {
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, nickname);
            rs = st.executeQuery();
            if(rs.next()) {
                System.out.println("중복된 닉네임");
                 JOptionPane.showMessageDialog(null, "중복된 닉네임입니다","회원가입 오류", 2);
                Dupi = true;
        } else {
            
                 Dupi = false;
            }
        }
                catch (SQLException ex) {
                
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Dupi;
    }
    private void PasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusGained
        // TODO add your handling code here:
        String pass = String.valueOf(PasswordField.getPassword());
        if(pass.trim().toLowerCase().equals(("password"))) {
            PasswordField.setText("");
            PasswordField.setForeground(Color.black);
        }
        Border idBorder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        PasswordField.setBorder(idBorder);
    }//GEN-LAST:event_PasswordFieldFocusGained

    private void ConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordActionPerformed

    private void BackKeyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackKeyMouseEntered
        // TODO add your handling code here:
         BackKey.setForeground(Color.gray);
    }//GEN-LAST:event_BackKeyMouseEntered

    private void BackKeyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackKeyMouseExited
        // TODO add your handling code here:
        BackKey.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_BackKeyMouseExited

    private void BackKeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackKeyMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackKeyMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-mouseX, y-mouseY);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JLabel BackKey;
    private javax.swing.JLabel Close;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel Minimize;
    private javax.swing.JTextField NickName;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nickNameLabel;
    // End of variables declaration//GEN-END:variables
}
